### ISSUE TITLE
Buy the hardware for the demo boxes

### ISSUE THREAD

**Issue by amcewen** [museuminabox/museuminabox#1]
Need to order the hardware (for the MVP at least).  That'll be...
- [x] Raspberry Pi 2 https://shop.pimoroni.com/collections/raspberry-pi/products/raspberry-pi-2-model-b
- [x] NFC/RFID reader http://skpang.co.uk/catalog/hf-rfid-module-sl030-33v-i2c-p-1065.html
- [x] Power supply https://shop.pimoroni.com/collections/raspberry-pi/products/raspberry-pi-universal-power-supply
- [x] Micro SD card - class 10, 8GB or bigger (maybe a 16GB to give us even more space for local audio/video?)
- [x] USB WiFi dongle (optional, but could let us get the boxes online https://shop.pimoroni.com/collections/raspberry-pi/products/official-raspberry-pi-wifi-dongle)
- [x] Speakers of some sort... 3.5mm stereo input, USB power maybe?
- [x] Case - https://shop.pimoroni.com/collections/raspberry-pi/products/pibow-coupe?variant=5202020929

Obviously we'll need a set of the above shopping list for each box.  If we're doing one with video too then we'll need an HDMI cable and projector or monitor of some sort.

**Comment by amcewen** [comment]
Ordering the NFC/RFID reader is dependent on issue #2 being resolved...

**Comment by amcewen** [comment]
Boxes for demo
1. Plays audio when tag presented, and stops when the tag is removed
2. Plays video (with audio) when tag is presented and stops when the tag
3. Fancier one with a touchscreen - exact working out tbd

Get enough kit for four

**Comment by amcewen** [comment]
Bah, I can't remember what colour we were supposed to get for the cases.  @george08 can you pick one from https://shop.pimoroni.com/collections/raspberry-pi/products/pibow-coupe?variant=5202020929 for me please?

**Comment by amcewen** [comment]
And how many RFID tags do we want?  Thinking that http://skpang.co.uk/catalog/rfid-label-1356mhz-mifare-1k-p-1080.html would work (and be the sort that I've used in the past - there will be other options for the future)

**Comment by amcewen** [comment]
Everything apart from the speakers ordered.  I'll tick them off as they arrive.

**Comment by amcewen** [comment]
I'm thinking that http://www.currys.co.uk/gbuk/computing-accessories/computer-accessories/pc-speakers/advent-asp20bk15-2-0-pc-speakers-10119644-pdt.html or http://www.maplin.co.uk/p/acme-by-krator-ss111-usb-20-speakers-5w-n97lh or http://www.amazon.co.uk/Logitech-980-000513-Z120-Stereo-Speakers/dp/B00544XKK4/ref=pd_cp_23_1?ie=UTF8&refRID=07HQ8QDGPXDBZW8WWH0V would be good for the speakers.  How many sets do we want?  Should we have one (or two?) of the boxes run from headphones instead?

**Comment by amcewen** [comment]
Waiting on microSD cards, and need to decide which speakers, but everything else arrived this morning :-)

**Comment by george08** [comment]
Sorry @amcewen - I've not been getting these comments emailed to me. Will start watching more better.

Smaller the better, I reckon, for speakers. The end goal is that everything will fit in something about shoebox size.

**Comment by amcewen** [comment]
Everything bought now.  The 32GB SD cards I'd ordered turned out to be Class 4, so slower than Class 10 :-(  Currently complaining to Amazon about that, so have bought a third 16GB Class 10 card instead to give us all we need for Tuesday.

Have two sets of USB-powered speakers for the not-boxed-up sets, and some tiny speakers and a little amp for the one getting boxed up.
