### ISSUE TITLE
Install Discourse forum

### ISSUE THREAD

**Issue by george08** [museuminabox/museuminabox#10]
Kickin' it, old school.

https://github.com/discourse/discourse

**Comment by portableant** [comment]
If you get stuck with that, let me know. I've installed it a few times now.

**Comment by george08** [comment]
Oh! That'd be very helpful,@portableant. Would you like to go ahead?

(I'll be interested in things like how it looks, and how people sign up to post, etc.)

**Comment by portableant** [comment]
You could use this if it saves you hassle https://www.discoursehosting.com/ 
If not send me details of where you are hosting etc, does it have docker? When do you want it up and running?

**Comment by george08** [comment]
I can't work out if we'd have to pay to host it ourselves... (other than existing hosting arrangements).

We're not set up to incur ongoing expenses yet, so would prefer to find a free option, if possible.

**Comment by portableant** [comment]
Okay, email me with your hosting setup when you get time.

**Comment by george08** [comment]
Hi @portableant what settings do you need specifically?

**Comment by portableant** [comment]
You need docker, RoR and ssh access.
