### ISSUE TITLE
Show list of boxes any object belongs to on /objects/x page

### ISSUE THREAD

**Issue by george08** [museuminabox/museuminabox#14]
E.g. http://museuminabox.herokuapp.com/objects/1

There are two positions for this data on the page:
1. In the right column under the main image
2. In the "Prints" table at the bottom. (But this is faked for December 8 prototype.)

**Comment by barnaclebarnes** [comment]
Was this done as part of #15? @george08 Let me know if anything else is needed by this or just close.

**Comment by george08** [comment]
Was hoping that instead of "Box 3" it could say the name of the box. 

We're still thinking through how Things, Prints and Boxes work, but you might imagine a "British Museum in a Box" box... i.e. a box with a name.

**Comment by barnaclebarnes** [comment]
@george08 The issue is that boxes don't have names right now. Happy to refactor if I can get some rules around how to name a box from existing fields or add a new field if needed.

**Comment by george08** [comment]
Oh yeah, of course :)

There will be "Collections" at some point... They're currently (oddly) labeled as "Museums" in the database, which was a silly idea on my part :)

**Comment by george08** [comment]
Redundant because V2.
