### ISSUE TITLE
Show prints of things on /objects/x

### ISSUE THREAD

**Issue by george08** [museuminabox/museuminabox#15]
You can see a table at the bottom of the /objects/show template...

https://museuminabox.herokuapp.com/objects/14

**Comment by george08** [comment]
Hi @barnaclebarnes - I haven't really asked for a remote ruby favour before, so am not sure what you need to know to get started.

You probably won't be surprised to hear that there's also a bit of a time crunch. We're trying to get our boxes and website together for an event next Tuesday, December 8.

There's a website online at the link above - not public yet. Any check-ins to the master branch are deployed automatically.

Let me know if you are able to help us out over the next day or two - time is of the essence! If you're into it. I can assign the stuff that's probably simple-ish for you to do...

**Comment by barnaclebarnes** [comment]
I've got a couple of hours free this morning. Assign me a couple of things!

**Comment by barnaclebarnes** [comment]
@george08 Is there a DB dump I can seed my local DB with? I have the app running locally on my machine now.

**Comment by barnaclebarnes** [comment]
@george08 See #16 

Merge if you're happy. There are 2 fields that I'm not sure where we get them from.

**Comment by george08** [comment]
@amcewen could you please help Glen connect to the db?

**Comment by george08** [comment]
Thanks @barnaclebarnes!

**Comment by barnaclebarnes** [comment]
Done - extra fields needed in #17
