### ISSUE TITLE
Object attribution: Er-Rum

### ISSUE THREAD

**Issue by portableant** [museuminabox/museuminabox#18]
Hey all,
I guess the object data for the Er-Rum mask is held in the db and not in code. There's a few errors here:
https://museuminabox.herokuapp.com/objects/18

The object is the Er-Rum mask and belongs to the Palestine Exploration Fund (http://www.pef.org.uk) and I the copyright is theirs not Micropasts. I can give you their logo if you want, it is CC-BY though.
Looking super, top work y'all. 
Dan

**Comment by george08** [comment]
Fixed in the DB, @portableant. If OK, pls close.
