### ISSUE TITLE
Choose the NFC/RFID reader for the demo boxes

### ISSUE THREAD

**Issue by amcewen** [museuminabox/museuminabox#2]
So far I've used http://skpang.co.uk/catalog/hf-rfid-module-sl030-33v-i2c-p-1065.html for my Raspberry Pi RFID projects.  I have code that works for that, but it only talks to RFID tags, not to NFC phones, so isn't as flexible as an NFC option.

I've recently started playing with http://www.ebay.co.uk/itm/PN532-NFC-RFID-Kit-V3-module-Raspberry-Pi-Arduino-NEW-/161778612132 which is an NFC reader.  There's also a physically larger (but functionally equivalent) option in http://www.ebay.co.uk/itm/NFC-RFID-Shield-Module-PN532-Breakout-Board-Expansion-Board-UK-SHIPIING-/261965908864 (we've used one of the latter with an Arduino at DoES Liverpool)

**Comment by amcewen** [comment]
I've actually got access to at least one, and most likely two, of the SL030 boards, so maybe the best option is to go with the NFC ones and if I don't have enough time to get the code written to use them for December, we can fall back to borrowing the SL030s?

**Comment by george08** [comment]
Hi @amcewen - thanks for this.

I'm imagining that the Brain won't need to talk directly to a phone. We'll just slap an NFC sticker on each object or postcard, and make sure the Brain can read them.

If someone happens to have a phone that can also read the NFC chip, fantastic.

That help?

---

I'm literally imagining a target painted on both the object and the Brain, so hopefully it's fairly obvious you're supposed to connect them. (Or something like that.)

**Comment by amcewen** [comment]
@george08 and I had a chat about it, and figured the tried-and-tested option was best to begin with, so we should get the SL030s.
