### ISSUE TITLE
Move DNS to heroku

### ISSUE THREAD

**Issue by george08** [museuminabox/museuminabox#20]
Need museuminabox.org live for tomorrow!

**Comment by george08** [comment]
Laughing Squid #98834 help ticket created a moment ago.

**Comment by amcewen** [comment]
This has only ever half-worked.  http://www.museuminabox.org works fine, but http://museuminabox.org redirects to museuminabox.herokuapp.com.

Doing some digging into it, it looks like www.museuminabox.org is set up right (as a CNAME entry in the DNS to point to museuminabox.herokuapp.com), but museuminabox.org has a DNS entry that points to a different server, and that server is then serving an HTTP 301 redirect to http://museuminabox.herokuapp.com/.

So I think we need to ask Laughing Squid to set the DNS for museuminabox.org to also be a CNAME to museuminabox.herokuapp.com (the same as www.museuminabox.org is).  @george08 can you ask them for that?  (Feel free to CC me in if that's better than you relaying tech info between us :-)

**Comment by george08** [comment]
A ha! Thanks Adrian. Can do.

g

...
George Oates
Director

Good, Form & Spectacle
+44 (0) 7478 325 990
gfns.uk

-----Original Message-----

**Comment by george08** [comment]
Here's what they told me:

> Scott Devaney, Apr 7, 11:08:
> Hello,
> Unfortunately setting a CNAME as the apex record of your domain is against RFC standards and our upstream provider Rackspace doesn't support using ALIAS records at this time.
> Here is the information on why a CNAME record can not be used as the apex record for your domain: http://serverfault.com/questions/613829/why-cant-a-cname-record-be-used-at-the-apex-aka-root-of-a-domain
> Here are other people who have had similar requests and how they have handled the situation: http://stackoverflow.com/questions/16022324/how-to-setup-dns-for-an-apex-domain-no-www-pointing-to-a-heroku-app
> Please let me know if I can be of any further assistance.
> Thanks,
> Scott

**Comment by george08** [comment]
Can we make museuminabox.org redirect to www.museuminabox.org or am I missing the point.

**Comment by amcewen** [comment]
I'd figured that the CNAME option would then let us decide which URL would be the canonical one, but wasn't sure if it would cause DNS problems (I've written more DNS clients than run DNS servers :-)

Good reply from Laughing Squid - and it seems that having them fix their HTTP redirect is the only real option.

So yes, asking them to change the redirect so that instead of redirecting to http://museuminabox.herokuapp.com it redirects to http://www.museuminabox.org should fix things.

**Comment by george08** [comment]
Scott has redirected museuminabox.org to www.museuminabox.org. Yeah!
