### ISSUE TITLE
If you're in a section, make the nav highlight that section

### ISSUE THREAD

**Issue by george08** [museuminabox/museuminabox#23]
There's already a hover CSS effect in the top nav bar. Wondering if that effect can be sticky when you're in that bit (but also still a link).

/museums, /museums/x
/objects, /objects/x
/boxes, /boxes/x

**Comment by barnaclebarnes** [comment]
@george08 Added `.active` class. CSS is not my friend so somebody else can add the styling ;-)
- [ ] Add style for `.active` class on menu 

I also added `byebug` in the gem file for debugging in dev. Helps a lot to add breakpoints to see what is going on.
