### ISSUE TITLE
Site throwing 500? 

### ISSUE THREAD

**Issue by george08** [museuminabox/museuminabox#30]
@barnaclebarnes - any chance it's something you said?
(Was working for me about 4 hours ago...)

**Comment by george08** [comment]
https://museuminabox.herokuapp.com
"We're sorry but something went wrong. Check the logs...)

(I'm poking at Heroku.)

**Comment by barnaclebarnes** [comment]
Probably, doh!

Do you have logs? or any error tracking?

**Comment by george08** [comment]
Just whatever Heroku gives us atm.

**Comment by george08** [comment]
(Could well be something I did! Cheeky to suggest otherwise.) :)

**Comment by barnaclebarnes** [comment]
Can you invite me to heroku so I can check out what the issue is? Works for me locally ;-)

**Comment by george08** [comment]
Sure - what's a good email?

**Comment by barnaclebarnes** [comment]
barnaclebarnes@mac.com mailto:barnaclebarnes@mc.com

Cheers

**Comment by george08** [comment]
They're different :) Sending to @mac.com.

**Comment by george08** [comment]
We also use Slack... Want to join?

**Comment by barnaclebarnes** [comment]
Yes - I’m on Slack as well. Same email address.

**Comment by george08** [comment]
Invited. I need to hit the sack now. Please let me know if you uncover anything! And thank you again for helping - it's been fantastic to have you join in.
