### ISSUE TITLE
Create a custom 500 error page

### ISSUE THREAD

**Issue by amcewen** [museuminabox/museuminabox#32]
For occasions when Heroku have done something weird to break the site (like now), we should show a nicer error page.

From @frankieroberto in slack:
incidentally, here’s how to customize the 500 error page: https://devcenter.heroku.com/articles/error-pages

(in short: upload file to S3/the internet somewhere and set a
ERROR_PAGE_URL env variable in Heroku

**Comment by george08** [comment]
@nebulousflynn You mentioned this last week? Did you figure it out?

**Comment by george08** [comment]
Closing this. Redundant, since V2.
