### ISSUE TITLE
A way for people to directly connect their phone / tablet / laptop to a brain over wifi

### ISSUE THREAD

**Issue by nebulousflynn** [museuminabox/museuminabox#37]
I.e. Each brain has could have its own WiFi address (e.g. "Brain1234") that you can connect to.  This could be for admin purposes (uploading and editing local content) but also for multiple people to view the same window (an HTML page) that updates as an object is booped.

**Comment by george08** [comment]
Working on it!

**Comment by george08** [comment]
Redundant because V2 + new Wifi config work that Adrian's doing.
