### ISSUE TITLE
Store Brain content online somewhere

### ISSUE THREAD

**Issue by amcewen** [museuminabox/museuminabox#45]
Rather than have to manually copy the video and audio files for the Brains over to each brain, we should hook them into the provisioning system so they're pulled down when the Brain is first set up (and also can be synchronized/updated automatically afterwards)

S3 looks like the simplest option, so we should extend the admin interface to allow uploading of content to S3 and store the URLs in the Object's model

**Comment by barnaclebarnes** [comment]
Try the paperclip gem - https://github.com/thoughtbot/paperclip for attachments. Super simple to set up and works with S3 out of the box.

**Comment by amcewen** [comment]
Thanks!  Good to see paperclip is still going strong - used it years back on a Rail 2 site :-)

However, judging by https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails it seems that it's not the best option for big files (and as some of ours will be video I expect we'll hit that).  jquery-file-upload is looking like the best candidate so far.

**Comment by barnaclebarnes** [comment]
Yeah, paperclip still works! There are other more elegant solutions out there but PC I find to be really easy. For large files it is generally OK if it is low volume but it looks like that isn't always the case on Heroku. 

BTW: if you need to transcode video/audio then look at AWS Elastic Transcoder. And for image derivatives Thumbor or IMGIX.
