### ISSUE TITLE
Website URL is confused

### ISSUE THREAD

**Issue by nebulousflynn** [museuminabox/museuminabox#50]
There is something up with the DNS or redirect, URL currently looks like this:

http://www.museuminabox.org.php56-18.dfw3-2.websitetestlink.com/wp-login.php

This is also breaking the icon font (used in tabs above main logo) in certain browsers.

**Comment by nebulousflynn** [comment]
this is also breaking some links in the WP admin - I can't get to the 'Edit CSS' page as there is some funky redirect loop happening

**Comment by george08** [comment]
@nebulousflynn can you tell me when you see a link like that? If i'm on museuminabox.org, it doesn't come up here.

I see it when I'm in WP admin though...

And, I can reproduce the CSS non-link too.

**Comment by george08** [comment]
BTW, at least if you go to "Editor" instead of "Edit CSS" you can edit the CSS...

http://www.museuminabox.org.php56-18.dfw3-2.websitetestlink.com/wp-admin/theme-editor.php

**Comment by nebulousflynn** [comment]
i get it when i try to log in at museuminabox.org/wp-admin - i get sent to:

http://www.museuminabox.org.php56-18.dfw3-2.websitetestlink.com/wp-login.php?redirect_to=http%3A%2F%2Fmuseuminabox.org%2Fwp-admin%2F&reauth=1

thanks for tip on css edits!
