### ISSUE TITLE
Add MIAB logo to the repository

### ISSUE THREAD

**Issue by amcewen** [museuminabox/museuminabox#8]
Any chance that we could add a copy of the Museum in a Box logo to the repository somewhere?  Or failing that, share it with me?

Vector format preferred (am hoping to get chance to laser-etch it onto things...)

**Comment by george08** [comment]
I've popped the .svg in /public.

**Comment by amcewen** [comment]
Logo received, and used - https://www.instagram.com/p/-3kRdIDVbP/
