### ISSUE TITLE
Create BOOP_LOG entry 

### ISSUE THREAD

**Issue by george08** [museuminabox/museuminabox#9]
Any time a print is booked on the brain, make a note of it.
- Box_ID
- Object_ID
- DateTime

When possible, upload the BOOP log to the Great Museum in the Sky.

Down the line, you could imagine an institution or a person with a box being able to see all the BOOPs that have happened to any object prints they're connected to.

**Comment by george08** [comment]
May need to consider some kind of permissions, so children can't be surveilled.

**Comment by amcewen** [comment]
Remaining work for this is in issue #28.
